# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  tools:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - test -f code/go/site/twcli || wget -O code/go/site/twcli https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v1.7.20/tailwindcss-extra-linux-x64
      - chmod +x code/go/site/twcli

  tsbuild:
    sources:
      - "**/*.ts"
    generates:
      - "bundles/**/*"
    cmds:
      - go run code/go/cmd/tsbuild/main.go
      - rm -rf code/go/site/static/js/bundles
      - mkdir -p code/go/site/static/js/bundles
      - cp -r bundles/datastar.js* code/go/site/static/js/bundles/
      - cp code/ts/library/package.json code/go/site/static/js/bundles/package.json

  css:
    dir: code/go/site
    sources:
      - "**/*.templ"
      - "**/*.md"
    generates:
      - "static/css/site.css"

    cmds:
      - ./twcli build -o static/css/site.css

  templ:
    env:
      TEMPL_EXPERIMENT: rawgo
    generates:
      - "**/*_templ.go"
    sources:
      - "**/*.templ"
    cmds:
      - templ generate .

  site:
    desc: Server hot reload
    env:
      ENV: dev
    method: none
    sources:
      - "**/*.go"
      - "**/*.md"
      - "go/site/static/**/*"
    deps:
      - tsbuild
      - templ
      - css

    cmds:
      - go mod tidy
      - go run code/go/cmd/site/main.go

  clean:
    cmds:
      - npx kill-port 4222

  default:
    desc: Default task
    deps:
      - site
