# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  tools:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/a-h/templ/cmd/templ@latest

  tsbuild:
    cmds:
      - go run go/cmd/tsbuild/main.go
